### ISSUE TITLE
set up project

### ISSUE THREAD

**Issue by bayanseder** [GSG-K3/Art-Gallery#7]
- Front-end 

- [ ] Install React using `npx create-react-app`
- [ ] Install react-router-dom using `npm i react-router-dom`
- [ ] Install axios using `npm i axios`
- [ ] Install Material-UI using `npm i @material-ui/core`
- [ ] Install  Eslint

**Comment by someyaaltous** [comment]
- Back-end
 - [ ] Install express js using ` npm i express`
- [ ] Install pg using `npm i pg` pg version  7.17.7
- [ ] Install env2 using ` npm i env2`
- [ ] Install bcrypt using ` npm i bcrypt`
